# Generated by Django 6.0.5 on 2026-05-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hash_api_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='api_key_created_at',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='api_key_hash',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='api_key_prefix',
        ),
    ]
