# Generated by Django 6.0.5 on 2026-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='api_key_prefix',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
